simplistic email-based error reporting

diff --git a/mbackup b/mbackup
--- a/mbackup
+++ b/mbackup
@@ -24,3 +24,8 @@ fi
 
 echo "[$log_date] Backing up $2 to $targetdir/$file..."
 mput -q -f $2 -H content-md5:$(cat $2 | openssl md5 -binary | openssl enc -base64) $targetdir/$file
+
+# Report errors during the mput stage. Configure the 'errors_email' variable in .manta_config
+if [ "$?" != "0" ]; then
+  echo "mbackup encountered errors while transferring $file to $targetdir." | mailx $ERRORS_EMAIL
+fi
